name: task_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.0
  provider: ^6.1.2
  surf_lint_rules: ^3.1.0
  uuid: ^4.5.1
  connectivity_plus: ^6.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
